### ISSUE TITLE
One of my players crashing client side everytime he breaks a manual grinder with a steel blade

### ISSUE THREAD

**Issue by ybronhaiasi** [HaydenBelanger/assemblylinemachines#36]
I'm running a server with Another Quality Modpack 3, version: 1.18.1 (1.2.2)
one of my players keeps crashing every time he tries to mess with your mod, so thought I'd send the details ur way.
looks like he was breaking a grinder with a steel blade, I havent messed with ur mod much yet, so I'm not sure what exactly he was doing. but hope this helps out in some way.

[09:23:53] [Server thread/WARN]: Mismatch in destroy block pos: BlockPos{x=433, y=69, z=-1965} BlockPos{x=434, y=69, z=-1965}
[09:23:53] [Server thread/WARN]: Mismatch in destroy block pos: BlockPos{x=433, y=69, z=-1965} BlockPos{x=434, y=69, z=-1965}
[09:24:22] [Server thread/INFO]: All players have been successfully backed up
[09:26:38] [Server thread/INFO]: Shananogans has reached level 26 in combat! [minecraft:overworld|x:685.19|y:25.00|z:-2042.36]
[09:27:08] [Server thread/INFO]: Saving the game (this may take a moment!)
[09:27:08] [Server thread/INFO]: Saved the game
[09:31:48] [Server thread/INFO]: <tarmadon> alright, here we go again
[09:31:54] [Server thread/ERROR]: Exception caught during firing event: 'me.haydenb.assemblylinemachines.registry.ConfigHandler$ALMClientConfig me.haydenb.assemblylinemachines.registry.ConfigHandler$ConfigHolder.getClientConfig()'
	Index: 8
	Listeners:
		0: HIGH
		1: net.minecraftforge.eventbus.EventBus$$Lambda$3760/0x00000008015ee4d0@3d5bf60b
		2: ASM: class dev.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		3: NORMAL
		4: ASM: class com.github.klikli_dev.occultism.handlers.LootEventHandler giveStoneToBlacksmith(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		5: net.minecraftforge.eventbus.EventBus$$Lambda$3760/0x00000008015ee4d0@314920d
		6: ASM: class com.direwolf20.buildinggadgets.common.events.ItemPickupHandler GetDrops(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		7: ASM: com.lothrazar.storagenetwork.registry.SsnEvents@5baf0d6e onEntityItemPickupEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		8: ASM: stepsword.mahoutsukai.handlers.ServerHandler@a425895 useItem(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		9: ASM: Block{naturesaura:pickup_stopper} onPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		10: ASM: vazkii.quark.content.tools.module.SeedPouchModule@6992cd8d onItemPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		11: ASM: com.lothrazar.cyclic.event.ItemEvents@48901aae onPlayerPickup(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		12: ASM: com.minecolonies.coremod.permissions.ColonyPermissionEventHandler@23bdfe3f on(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
		13: LOW
		14: net.minecraftforge.eventbus.EventBus$$Lambda$3760/0x00000008015ee4d0@5ade26e9
		15: LOWEST
		16: ASM: class com.hollingsworth.arsnouveau.common.event.EventHandler itemPickupEvent(Lnet/minecraftforge/event/entity/player/EntityItemPickupEvent;)V
java.lang.NoSuchMethodError: 'me.haydenb.assemblylinemachines.registry.ConfigHandler$ALMClientConfig me.haydenb.assemblylinemachines.registry.ConfigHandler$ConfigHolder.getClientConfig()'
	at TRANSFORMER/assemblylinemachines@1.18-1.3.6/me.haydenb.assemblylinemachines.block.rudimentary.BlockHandGrinder.m_7705_(BlockHandGrinder.java:60)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.item.BlockItem.m_5524_(BlockItem.java:193)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.item.Item.m_5671_(Item.java:217)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.item.Item.m_7626_(Item.java:268)
	at TRANSFORMER/mahoutsukai@1.18.1-v1.33.7/stepsword.mahoutsukai.effects.secret.GeasEffect.hasGeas(GeasEffect.java:141)
	at TRANSFORMER/mahoutsukai@1.18.1-v1.33.7/stepsword.mahoutsukai.effects.secret.GeasEffect.geasItem(GeasEffect.java:49)
	at TRANSFORMER/mahoutsukai@1.18.1-v1.33.7/stepsword.mahoutsukai.handlers.ServerHandler.useItem(ServerHandler.java:391)
	at net.minecraftforge.eventbus.ASMEventHandler_1195_ServerHandler_useItem_EntityItemPickupEvent.invoke(.dynamic)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at MC-BOOTSTRAP/eventbus@5.0.3/net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at TRANSFORMER/forge@39.0.10/net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:437)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.item.ItemEntity.m_6123_(ItemEntity.java:325)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_36277_(Player.java:555)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_8107_(Player.java:522)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.world.entity.player.Player.m_8119_(Player.java:234)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.network.Connection.m_129483_(Connection.java:233)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668)
	at TRANSFORMER/minecraft@1.18.1/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258)
	at java.base/java.lang.Thread.run(Thread.java:833)

[09:31:54] [Server thread/WARN]: Failed to handle packet for /24.16.69.181:29549
net.minecraft.ReportedException: Ticking player
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:502) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:206) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.network.Connection.m_129483_(Connection.java:233) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:328) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchMethodError: 'me.haydenb.assemblylinemachines.registry.ConfigHandler$ALMClientConfig me.haydenb.assemblylinemachines.registry.ConfigHandler$ConfigHolder.getClientConfig()'
	at me.haydenb.assemblylinemachines.block.rudimentary.BlockHandGrinder.m_7705_(BlockHandGrinder.java:60) ~[assemblylinemachines-1.18-1.3.6.jar%2352!:?]
	at net.minecraft.world.item.BlockItem.m_5524_(BlockItem.java:193) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.world.item.Item.m_5671_(Item.java:217) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.world.item.Item.m_7626_(Item.java:268) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at stepsword.mahoutsukai.effects.secret.GeasEffect.hasGeas(GeasEffect.java:141) ~[mahoutsukai-1.18.1-v1.33.7.jar%23208!:1.18.1-v1.33.7]
	at stepsword.mahoutsukai.effects.secret.GeasEffect.geasItem(GeasEffect.java:49) ~[mahoutsukai-1.18.1-v1.33.7.jar%23208!:1.18.1-v1.33.7]
	at stepsword.mahoutsukai.handlers.ServerHandler.useItem(ServerHandler.java:391) ~[mahoutsukai-1.18.1-v1.33.7.jar%23208!:1.18.1-v1.33.7]
	at net.minecraftforge.eventbus.ASMEventHandler_1195_ServerHandler_useItem_EntityItemPickupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.3.jar%232!:?]
	at net.minecraftforge.event.ForgeEventFactory.onItemPickup(ForgeEventFactory.java:437) ~[forge-1.18.1-39.0.10-universal.jar%23330!:?]
	at net.minecraft.world.entity.item.ItemEntity.m_6123_(ItemEntity.java:325) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.world.entity.player.Player.m_36277_(Player.java:555) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.world.entity.player.Player.m_8107_(Player.java:522) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2243) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:234) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:439) ~[server-1.18.1-20211210.034407-srg.jar%23326!:?]
	... 9 more
[09:31:55] [Server thread/INFO]: tarmadon lost connection: Internal server error
[09:31:55] [Server thread/INFO]: tarmadon left the game
[09:37:07] [Server thread/INFO]: Saving the game (this may take a moment!)
[09:37:08] [Server thread/INFO]: Saved the game
[09:42:50] [Netty Epoll Server IO #3/WARN]: Login payload for Registry minecraft:item is using 44.8079% of max allowed vanilla size
[09:42:50] [Netty Epoll Server IO #3/WARN]: Login payload for Registry minecraft:block is using 32.8912% of max allowed vanilla size
[09:42:51] [User Authenticator #7/INFO]: UUID of player tarmadon is 4feb2664-16cb-4524-aab1-68a3583804c3
[09:43:15] [Server thread/INFO]: Ch1ck3nL0rd lost connection: Disconnected
[09:43:15] [Server thread/INFO]: Ch1ck3nL0rd left the game
[09:43:31] [Server thread/INFO]: Shananogans has reached level 28 in agility! [minecraft:overworld|x:514.70|y:70.93|z:-2018.37]
[09:43:39] [Server thread/INFO]: Using new advancement loading for net.minecraft.server.PlayerAdvancements@b5da8ca
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: wstweaks:wither_skeleton_skull removed now.
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: wstweaks:blaze_blade removed now.
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: wstweaks:lava_blade removed now.
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: ender_bags:white_bag removed now.
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: wstweaks:wither_skeleton_skull removed now.
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: wstweaks:blaze_blade removed now.
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: wstweaks:lava_blade removed now.
[09:43:39] [Server thread/ERROR]: Tried to load unrecognized recipe: ender_bags:white_bag removed now.
[09:43:39] [Server thread/INFO]: tarmadon[/24.16.69.181:25690] logged in with entity id 16015 at (394.7344572590991, 66.0, -1998.287588626765)
[09:43:39] [Server thread/INFO]: tarmadon joined the game
[09:43:39] [Server thread/INFO]: Sent config to 'tarmadon'.
[09:43:39] [Server thread/INFO]: Syncing config to tarmadon (4feb2664-16cb-4524-aab1-68a3583804c3)
[09:44:22] [Server thread/INFO]: All players have been successfully backed up
[09:45:56] [Server thread/INFO]: Blight Squid has died
[09:47:07] [Server thread/INFO]: Saving the game (this may take a moment!)
[09:47:08] [Server thread/INFO]: Saved the game</tarmadon>

**Comment by DamianBerek** [comment]
have the same issue as well 4 other players on my server

**Comment by HaydenBelanger** [comment]
I will be reverting a recent change I made that will fix this issue. Apologies for the long time to fix, I was away from my home and could not push a fix for this.

**Comment by DamianBerek** [comment]
do you have any eta on release of fix ??

**Comment by HaydenBelanger** [comment]
I am pushing the fix today.
