### ISSUE TITLE
Interactor Crashes Game, Major Bug

### ISSUE THREAD

**Issue by LapisPhoenix** [HaydenBelanger/assemblylinemachines#39]
Please fix this, I **Cannot** enter my world, all my progress is gone right now..

![image](https://user-images.githubusercontent.com/88260244/150624749-c5890843-82f1-46f9-8aa6-02ca0413082d.png)

The game crashed whilst ticking block entity
Error: java.lang.NullPointerException: Cannot invoke "java.lang.ref.WeakReference.get()" because "this.fpRef" is null
Exit Code: -1

Everything was working fine until I placed down an Interactor, placed a netherite sword with Sharpness II and Fire Aspect I

-- Head --
Thread: Server thread
Stacktrace:
	at me.haydenb.assemblylinemachines.block.automation.BlockInteractor$TEInteractor.tick(BlockInteractor.java:184) ~[assemblylinemachines-1.17.1-1.3.0.2.jar%2360!:?] {re:classloading}
	at me.haydenb.assemblylinemachines.block.helpers.BlockTileEntity$1.m_155252_(BlockTileEntity.java:73) ~[assemblylinemachines-1.17.1-1.3.0.2.jar%2360!:?] {re:classloading}
-- Block entity being ticked --
Details:
	Name: assemblylinemachines:interactor // me.haydenb.assemblylinemachines.block.automation.BlockInteractor.TEInteractor
	Block: Block{assemblylinemachines:interactor}[facing=north,fluid=none]
	Block location: World: (241,59,-31), Section: (at 1,11,1 in 15,3,-2; chunk contains blocks 240,0,-32 to 255,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Block: Block{assemblylinemachines:interactor}[facing=north,fluid=none]
	Block location: World: (241,59,-31), Section: (at 1,11,1 in 15,3,-2; chunk contains blocks 240,0,-32 to 255,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
Stacktrace:
	at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.m_142224_(LevelChunk.java:844) ~[client-1.17.1-20210706.113038-srg.jar%23122!:?] {re:classloading}
	at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.m_142224_(LevelChunk.java:932) ~[client-1.17.1-20210706.113038-srg.jar%23122!:?] {re:classloading}
	at net.minecraft.world.level.Level.m_46463_(Level.java:475) ~[client-1.17.1-20210706.113038-srg.jar%23122!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinWorld,pl:mixin:A}
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:391) ~[client-1.17.1-20210706.113038-srg.jar%23122!:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:enhancedcelestials.mixins.json:MixinServerWorld,pl:mixin:A}

**Comment by HaydenBelanger** [comment]
This bug was fixed in 1.17.1-1.3.0.4 and 1.18-1.3.3.

**Comment by Enterprise12nx01** [comment]
This makes your mod unplayable..and you didnt back port it? i have the same issue
