### ISSUE TITLE
Manual Grinder Crash

### ISSUE THREAD

**Issue by Tobanyi** [HaydenBelanger/assemblylinemachines#40]
When placing a grinder, or loading a map with one placed

---- Minecraft Crash Report ----
// You're mean.

Time: 1/23/22, 1:13 PM
Description: Exception in server tick loop

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag net.minecraft.world.level.block.entity.BlockEntity.save(net.minecraft.nbt.CompoundTag)'
	at me.haydenb.assemblylinemachines.block.helpers.BasicTileEntity.save(BasicTileEntity.java:49) ~[assemblylinemachines-1.18-1.3.6.jar%2359!/:?] {re:classloading}
	at me.haydenb.assemblylinemachines.block.helpers.BasicTileEntity.m_5995_(BasicTileEntity.java:37) ~[assemblylinemachines-1.18-1.3.6.jar%2359!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData$BlockEntityInfo.m_195691_(ClientboundLevelChunkPacketData.java:153) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:mixin,re:classloading,pl:mixin:APP:supplementaries.mixins.json:ChunkHolderMixin,pl:mixin:A}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkPacketData.<init>(ClientboundLevelChunkPacketData.java:44) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ClientboundLevelChunkWithLightPacket.<init>(ClientboundLevelChunkWithLightPacket.java:24) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.level.ChunkMap.m_183760_(ChunkMap.java:1125) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_183754_(ChunkMap.java:785) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_140192_(ChunkMap.java:923) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.m_140199_(ChunkMap.java:1045) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerChunkCache.m_8463_(ServerChunkCache.java:458) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1551) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel$EntityCallbacks.m_141985_(ServerLevel.java:1534) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.m_157575_(PersistentEntitySectionManager.java:135) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addEntityWithoutEvent(PersistentEntitySectionManager.java:98) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.world.level.entity.PersistentEntitySectionManager.addNewEntityWithoutEvent(PersistentEntitySectionManager.java:76) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.level.ServerLevel.m_8853_(ServerLevel.java:827) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
	at net.minecraft.server.level.ServerLevel.m_8834_(ServerLevel.java:771) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer,re:mixin,pl:accesstransformer:B,xf:fml:sereneseasons:temperature_transformer}
	at net.minecraft.server.players.PlayerList.m_11261_(PlayerList.java:190) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,xf:fml:xaeroworldmap:xaero_wm_playerlist_sendworldinfo,xf:fml:xaerominimap:xaero_playerlist_sendworldinfo}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_143699_(ServerLoginPacketListenerImpl.java:138) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10055_(ServerLoginPacketListenerImpl.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.m_10050_(ServerLoginPacketListenerImpl.java:69) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.network.Connection.m_129483_(Connection.java:229) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:mixin,re:classloading,pl:mixin:A}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:882) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:808) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:86) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23115!/:?] {re:classloading,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.18.1
	Minecraft Version ID: 1.18.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 5241024000 bytes (4998 MiB) / 8455716864 bytes (8064 MiB) up to 8455716864 bytes (8064 MiB)
	CPUs: 8
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1050 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1c82
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7168
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 37566.46
	Virtual memory used (MB): 17994.63
	Swap memory total (MB): 4864.00
	Swap memory used (MB): 1.24
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8064m -Xms256m
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Alator'/216, l='ServerLevel[New World]', x=6.35, y=66.00, z=2.90]]
	Data Packs: vanilla, mod:hexerei, mod:farmersdelight, mod:seedfix, mod:enchdesc, mod:theoneprobe (incompatible), mod:ambientsounds (incompatible), mod:mousetweaks, mod:titanium (incompatible), mod:telepads (incompatible), mod:endrem (incompatible), mod:creativecore, mod:jei (incompatible), mod:doggytalents, mod:domum_ornamentum (incompatible), mod:curios, mod:patchouli, mod:essentials (incompatible), mod:blockui, mod:xaerominimap, mod:energymeter, mod:xaeroworldmap, mod:sereneseasons (incompatible), mod:assemblylinemachines (incompatible), mod:structurize, mod:multipiston (incompatible), mod:ambientenvironment (incompatible), mod:minecolonies (incompatible), mod:magical_torches, mod:occultism, mod:functionalstorage, mod:jeresources, mod:dragonfight (incompatible), mod:crossroads (incompatible), mod:forge, mod:appleskin (incompatible), mod:toms_storage, mod:fastleafdecay, mod:supplementaries (incompatible), mod:geckolib3 (incompatible), mod:selene (incompatible), mod:geolosys (incompatible), mod:supermartijn642configlib, mod:lootbeams, mod:stonechest, mod:cloth_config (incompatible), mod:supermartijn642corelib, mod:architectury (incompatible), mod:lightoverlay (incompatible), mod:chunkloaders (incompatible)
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	ModLauncher: 9.1.0+9.1.0+main.6690ee51
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		 mixin PLUGINSERVICE 
		 eventbus PLUGINSERVICE 
		 object_holder_definalize PLUGINSERVICE 
		 runtime_enum_extender PLUGINSERVICE 
		 capability_token_subclass PLUGINSERVICE 
		 accesstransformer PLUGINSERVICE 
		 runtimedistcleaner PLUGINSERVICE 
		 mixin TRANSFORMATIONSERVICE 
		 fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
	Mod List: 
		hexerei-0.1.13.jar                                |Hexerei                       |hexerei                       |0.1.13              |DONE      |Manifest: NOSIGNATURE
		Amplified Nether 1.0.1 ~ Forge.jar                |Amplified Nether + Seed Fix   |seedfix                       |0.0NONE             |DONE      |Manifest: NOSIGNATURE
		telepads-1.18.1-5.0.1.0.jar                       |Telepads                      |telepads                      |1.18.1-5.0.1.0      |DONE      |Manifest: NOSIGNATURE
		supermartijn642configlib-1.0.9-mc1.18.jar         |SuperMartijn642's Config Lib  |supermartijn642configlib      |1.0.9               |DONE      |Manifest: NOSIGNATURE
		jei-1.18.1-9.2.1.69.jar                           |Just Enough Items             |jei                           |9.2.1.69            |DONE      |Manifest: NOSIGNATURE
		DoggyTalents-1.18.1-2.4.2.jar                     |Doggy Talents 2               |doggytalents                  |2.4.2               |DONE      |Manifest: NOSIGNATURE
		essentials-1.18.1-2.13.3.jar                      |Essentials                    |essentials                    |1.18.1-2.13.3       |DONE      |Manifest: NOSIGNATURE
		XaerosWorldMap_1.20.0_Forge_1.18.jar              |Xaero's World Map             |xaeroworldmap                 |1.20.0              |DONE      |Manifest: NOSIGNATURE
		SereneSeasons-1.18.1-6.0.0.10-universal.jar       |Serene Seasons                |sereneseasons                 |1.18.1-6.0.0.10     |DONE      |Manifest: NOSIGNATURE
		assemblylinemachines-1.18-1.3.7.jar               |Assembly Line Machines        |assemblylinemachines          |1.18-1.3.7          |DONE      |Manifest: NOSIGNATURE
		lootbeams-1.18.1-release-jan1522.jar              |LootBeams                     |lootbeams                     |1.18.1              |DONE      |Manifest: NOSIGNATURE
		StoneChest-1.18.1-1.1.0.jar                       |Stone Chest                   |stonechest                    |1.1.0               |DONE      |Manifest: NOSIGNATURE
		JustEnoughResources-1.18.1-0.13.1.141.jar         |Just Enough Resources         |jeresources                   |0.13.1.141          |DONE      |Manifest: NOSIGNATURE
		dragonfight-1.18-1.7.jar                          |dragonfight mod               |dragonfight                   |1.18-1.7            |DONE      |Manifest: NOSIGNATURE
		crossroads-1.18.1-2.7.2.jar                       |Crossroads                    |crossroads                    |1.18.1-2.7.2        |DONE      |Manifest: NOSIGNATURE
		cloth-config-6.1.50-forge.jar                     |Cloth Config v4 API           |cloth_config                  |6.1.50              |DONE      |Manifest: NOSIGNATURE
		forge-1.18.1-39.0.58-universal.jar                |Forge                         |forge                         |39.0.58             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		supplementaries-1.18.1-1.1.9.jar                  |Supplementaries               |supplementaries               |1.1.9               |DONE      |Manifest: NOSIGNATURE
		selene-1.18-1.12.0.jar                            |Selene                        |selene                        |1.18-1.12.0         |DONE      |Manifest: NOSIGNATURE
		client-1.18.1-20211210.034407-srg.jar             |Minecraft                     |minecraft                     |1.18.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.18.1-1.0.3.jar                   |Farmer's Delight              |farmersdelight                |1.18.1-1.0.3        |DONE      |Manifest: NOSIGNATURE
		EnchantmentDescriptions-Forge-1.18.1-9.0.11.jar   |EnchantmentDescriptions       |enchdesc                      |9.0.11              |DONE      |Manifest: eb:c4:b1:67:8b:f9:0c:db:dc:4f:01:b1:8e:61:64:39:4c:10:85:0b:a6:c4:c7:48:f0:fa:95:f2:cb:08:3a:e5
		theoneprobe-1.18-5.0.3.jar                        |The One Probe                 |theoneprobe                   |1.18-5.0.3          |DONE      |Manifest: NOSIGNATURE
		AmbientSounds_v5.0.4_mc1.18.1.jar                 |Ambient Sounds                |ambientsounds                 |3.0.3               |DONE      |Manifest: NOSIGNATURE
		MouseTweaks-forge-mc1.18-2.21.jar                 |Mouse Tweaks                  |mousetweaks                   |2.21                |DONE      |Manifest: NOSIGNATURE
		titanium-1.18-3.4.0-27.jar                        |Titanium                      |titanium                      |3.4.0               |DONE      |Manifest: NOSIGNATURE
		Geolosys-1.18.1-7.0.1-beta-2.jar                  |Geolosys                      |geolosys                      |7.0.1-beta-2        |DONE      |Manifest: NOSIGNATURE
		endrem_forge-5.0.1-R-1.18.1.jar                   |End Remastered                |endrem                        |5.0-R-1.18.1        |DONE      |Manifest: NOSIGNATURE
		CreativeCore_v2.4.1_mc1.18.1.jar                  |CreativeCore                  |creativecore                  |2.4.0               |DONE      |Manifest: NOSIGNATURE
		supermartijn642corelib-1.0.16a-mc1.18.jar         |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.0.16a             |DONE      |Manifest: NOSIGNATURE
		domum_ornamentum-1.18.1-1.0.39-ALPHA-universal.jar|Domum Ornamentum              |domum_ornamentum              |1.18.1-1.0.39-ALPHA |DONE      |Manifest: NOSIGNATURE
		curios-forge-1.18.1-5.0.6.0.jar                   |Curios API                    |curios                        |1.18.1-5.0.6.0      |DONE      |Manifest: NOSIGNATURE
		Patchouli-1.18.1-64.jar                           |Patchouli                     |patchouli                     |1.18.1-64           |DONE      |Manifest: NOSIGNATURE
		blockui-1.18-0.0.34-ALPHA.jar                     |UI Library Mod                |blockui                       |1.18-0.0.34-ALPHA   |DONE      |Manifest: NOSIGNATURE
		Xaeros_Minimap_22.1.0_Forge_1.18.jar              |Xaero's Minimap               |xaerominimap                  |22.1.0              |DONE      |Manifest: NOSIGNATURE
		energymeter-1.18.1-3.1.0.jar                      |Energy Meter                  |energymeter                   |3.1.0               |DONE      |Manifest: NOSIGNATURE
		structurize-1.18.1-1.0.326-ALPHA.jar              |Structurize                   |structurize                   |1.18.1-1.0.326-ALPHA|DONE      |Manifest: NOSIGNATURE
		multi-piston-1.18-1.2.2-ALPHA.jar                 |Multi-Piston                  |multipiston                   |1.18-1.2.2-ALPHA    |DONE      |Manifest: NOSIGNATURE
		AmbientEnvironment-forge-1.18.1-7.0.4.jar         |Ambient Environment           |ambientenvironment            |7.0.4               |DONE      |Manifest: NOSIGNATURE
		minecolonies-1.18.1-1.0.360-ALPHA.jar             |MineColonies                  |minecolonies                  |1.18.1-1.0.360-ALPHA|DONE      |Manifest: NOSIGNATURE
		architectury-3.4.9.jar                            |Architectury                  |architectury                  |3.4.9               |DONE      |Manifest: NOSIGNATURE
		appleskin-forge-mc1.18-2.2.0.jar                  |AppleSkin                     |appleskin                     |2.2.0               |DONE      |Manifest: NOSIGNATURE
		MagicalTorches-1.18.1-2.0.1.jar                   |Magical Torches               |magical_torches               |2.0.1               |DONE      |Manifest: NOSIGNATURE
		occultism-1.18.1-1.25.5.jar                       |Occultism                     |occultism                     |1.18.1-1.25.5       |DONE      |Manifest: NOSIGNATURE
		functionalstorage-1.18.1-0.0.9.jar                |Functional Storage            |functionalstorage             |1.18.1-0.0.9        |DONE      |Manifest: NOSIGNATURE
		light-overlay-6.0.4-forge.jar                     |Light Overlay                 |lightoverlay                  |6.0.4               |DONE      |Manifest: NOSIGNATURE
		chunkloaders-1.1.9-mc1.18.jar                     |Chunk Loaders                 |chunkloaders                  |1.1.9               |DONE      |Manifest: NOSIGNATURE
		toms_storage-1.18-1.2.23.jar                      |Tom's Simple Storage Mod      |toms_storage                  |1.2.23              |DONE      |Manifest: NOSIGNATURE
		FastLeafDecay-27.2.jar                            |FastLeafDecay                 |fastleafdecay                 |27.2                |DONE      |Manifest: NOSIGNATURE
		geckolib-1.18-forge-3.0.7.jar                     |GeckoLib                      |geckolib3                     |3.0.7               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 777c4249-40ea-4458-b6c8-964e67bbac71
	FML: 39.0
	Forge: net.minecraftforge:39.0.58

**Comment by HaydenBelanger** [comment]
This will be fixed in the next version.
