### ISSUE TITLE
Ethene and other fluids not displaying in JEI (1.18.2)

### ISSUE THREAD

**Issue by loldev69** [HaydenBelanger/assemblylinemachines#87]
Relevant error log:

> [Render thread/ERROR] [me.je.co.re.FluidTankRenderer/]: Failed to get tooltip for fluid: FluidStack{Fluid=Propylene, Amount=1000}
java.lang.NullPointerException: Cannot invoke "java.util.function.Supplier.get()" because "this.flowing" is null
	at net.minecraftforge.fluids.ForgeFlowingFluid.m_6212_(ForgeFlowingFluid.java:132) ~[forge-1.18.2-40.2.0-universal.jar%23174!/:?] {re:classloading}
	at mezz.jei.common.render.FluidTankRenderer.getTooltip(FluidTankRenderer.java:187) ~[jei-1.18.2-forge-10.2.1.1004.jar%23114!/:10.2.1.1004] {re:classloading}
	at mezz.jei.common.ingredients.IngredientInformationUtil.getTooltipStrings(IngredientInformationUtil.java:30) ~[jei-1.18.2-forge-10.2.1.1004.jar%23114!/:10.2.1.1004] {re:classloading}
	at mezz.jei.common.ingredients.ListElementInfo.getTooltipStrings(ListElementInfo.java:112) ~[jei-1.18.2-forge-10.2.1.1004.jar%23114!/:10.2.1.1004] {re:classloading}

The following four fluids appear to be affected: ethane, ethylene, propane, and propylene.
The affected fluids show up in JEI without name (with debug tooltips, not even their ID shows up) and without icon, but otherwise seem to function properly.
Looking at [this file](https://github.com/HaydenBelanger/assemblylinemachines/blob/1.18.2-dev/src/main/java/me/haydenb/assemblylinemachines/registry/Registry.java), it seems that those four fluids were registered in a different way than the rest, which might be the cause of the bug.

**Comment by HaydenBelanger** [comment]
Fixed in 1.19 releases. We're no longer updating 1.18.2.
